spring:
  application:
    name: purchase-order-service
  profiles:
    active: dev # Perfil por defecto

---
# Configuración para Desarrollo (Local)
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    #que cree la base de datos localmente automaticamente
    url: jdbc:mysql://localhost:3306/purchase_db?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

---
# Configuración para Producción (Docker)
spring:
  config:
    activate:
      on-profile: prod
  datasource:

    url: jdbc:mysql://mysqldb:3306/purchase_db?serverTimezone=UTC
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false